apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr
  namespace: homarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      labels:
        app: homarr
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: homarr
          image: ghcr.io/homarr-labs/homarr:latest
          envFrom:
            - configMapRef:
                name: homarr-configmap
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /data
              name: homarr-data
      volumes:
        - name: homarr-data
          persistentVolumeClaim:
            claimName: homarr-data