apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:yYa3x/A1xhScZDNc/nA0Y5FMDCDCR95tM3uvoOQUfIUFG1RKfdp+t5unQak/4r9aI0ye0FBg5CZB37v+PH3TTu3JAtvlbl9Kl6N8F9+vg8sFXPd32fITtVS8e9IipXnjkCC2p3OjjNmw75DGqGdmom9XsMHq75MT2FogeX0ypz4lVTlBjGwMc/ljEnhAZxyTfZCXLH0VfOqNBh8WmBsX8I11lhU0w4RTuhLcMIuRda3gxU32jh9+g+G5qI4Q+vCH9C+Mip0cS7F7ZGdmxJqnlUdv027F2/yNJGvbmO4axt6ScXsn8o41a6kPKXk=,iv:WE0cih2Yqh4PZv/J7vElJ3JiRjqtadGEOvXkM8BcoCM=,tag:4E18gooTOTc9iGkUqHh8ug==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NXhpRzBCcHRoSWNwbnEz
            Z1RCMUYyQ3lXV1g5LzBhcjJpb1U4eXZyenhBCmlpczFpODZpQWZ3VVkwQUpaVU9N
            eFo1TzNVSGJIZ05BcWJoclhMYUZkUUUKLS0tIHd1QmlQNk12NUV6ZHZLK3R2cVdj
            dTV1cngvT1lGMTRXSURqaUhNREtWaXMKw7/ByWPOsNPxC2wwblkEi74/LaO/4m1o
            Gj/XUN1s0qdbtbEt4WEYuaYL32AyoO4V8Roz9kMloh8VD8qZ6z7hcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16lgz0kljjnxc6x858p40pqm020rr8vj3dm2ndn3laryvgnrmkcmst8vrs8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiT2FMZjIxY1l2a2hSbUI1
            QTgwSlpyYlJwRmF3L2FtU3Z4R1NwOExPc2dJCnZpK0gyRGVyNGJ6QzFEUUg1QzJ6
            NVVzVUJJbTVwcUNRSEZYaExDaE9rTVUKLS0tIGNlN005b2RZK2pDN3FweC9qL2pQ
            Tm94Sms0RjAyd0ttMUtCcEcvSkd3N3cK0tGqzCzshdejZpHEnGvDQJinFXGssaMV
            wJ/nmD6ajd44PrMSL5YzNjv3nVpIPQJMy4G3AXZ8GJik33NkjHrXIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gdgzwd806x9yf6nd7dujuv6wcvnstffwa2eayelgg66cssl6xyaqh6eq96
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T11:39:22Z"
    mac: ENC[AES256_GCM,data:o6kWVdltUSjJscT+qIgF1HU2OLM1KhPxSo0Qryey1fksMjsv2GsR0hwYJHLQpOvvDXAvAgdLD2mEgko0Xb3wbJoveqiWdWalzFHlxZRrovdhZ7GbCslbvYAX1QD2oJv6ih+z9RANXbuNZSc1PO5ztEukM+jme72eEY5g9QSuSNw=,iv:RHD6NhhQwX2AYuzY8ra7fKAGLUM1o2HZlOsZBM2J59Y=,tag:8PSUMCZuFYZdJeu1Ylg7NQ==,type:str]
    version: 3.13.0
