apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:m2FaOu+mnBuVvvGa6TT+vrcIBu+leMIxmAt+1TUSiyu+Od1937PTy2KtmyR8b8s7ictmjbL0p2sjmIsgBvogluRUqQC8EF7xvo8VuEWGbunZYOfMMNon8xcHtWCMXcCSTHAS9WUyrrNVab1WrJ429dT8IXI0dFDdJfFgTGoqz7UXOcHUTn3RclnmCGfqvqGIiFsvTygD9yhPiLZREjYn0JNhT+8Cl8V0i2FJmZqygEnvaK0B5xM3h6p8ef0vK8fG/iJFu1atKKtdw4ihwmzuxHK0iibNfyGsfNrhLE1njBd78xi6qjqHgrt49E8=,iv:mR/r7dmSPYPP2FrYQkw2RYxbtc6lj1oSHVQx9CdPkWo=,tag:rO7R60rdC90XfZvN3NO9dQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbnY3bitVTmhXdThoblI0
            aFhydFk3ZW5lSitRWkp1dDZCR1R1UEZuaFdFClNjY0MzR0RORXkrSTVNQ1E4MFBw
            N1RDRmxrWlcyNWhTK0RjMGxmMWd2MTQKLS0tIERYV2NCZStuYWs3TW15T0ljWmhq
            VFprQWx1cElkZWJtRDB0amZuOWwwTkUKyKwU/m6Pxrzg7tyywa/023H20FsyJJko
            7E1I902UndvRnhmF3xZHwKvUfpNh70NOJlOius7ij4+oyAbp44JMtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16lgz0kljjnxc6x858p40pqm020rr8vj3dm2ndn3laryvgnrmkcmst8vrs8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybkZTc0tNSmFFcjNzMmlS
            TzBMVW9DcTNMQkU5VVJpSm8vU09SMzZHaUdzClZrdVliQkpnQW0vZm9qRTJvSGky
            dURaUEt0SXBacWVkc2tpRnBFcGVRZmMKLS0tIG9ZcVl3b29paGZXWjJFOTd0V1hV
            bVl0cE14K2x4bDEramtpZ011QVBYNkEKJae6XQZUW8FEDuOR5QkE9BRnjeVon/CH
            USjJuYtVwpw1ArZ0asWX83JRQF7h6GG1VGJY9aTQwo2peVAv9LUWmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gdgzwd806x9yf6nd7dujuv6wcvnstffwa2eayelgg66cssl6xyaqh6eq96
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T12:58:35Z"
    mac: ENC[AES256_GCM,data:7k+MU288OxEPIikPBovmr8kx29VhjlmAxf7452IN/Il7OJhevFS4E3MVL06QdJEVGGz/FeaAlByxN1Mo5EmO5YqUihZN3zGQd8gX4NdDiRyTqm4+5mJDqnx5/xWgGncnKs3r3T6j124wZwu6J9ihZPRIZHrS0aEvq4Cno3pSQQ8=,iv:dd+LqkF7fjF8NncQFMo1JJUzjWWq5n7Qsi9knOrxneE=,tag:OpWhZ/3XcBu5imvfFRCE/w==,type:str]
    version: 3.13.0
