apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:Sz0JL1PqKOGpDVwHCUXX+he80VbI72J9VIC2VSGOV4q6HZU78c9V6+qwYaQyspLuuyBI7yVcM+U2wnx6uGZvf3l8cXAkU9U1HgQ7Aq0z+dvuAKD42FSqgbt4XNfP8OEQcr2/CwnY6oBbPj7GWN6MEQ6WCY9PFeHaiWArgJ9XKdHgXesOi1ycqZ8uQh1Gvhy+MihdCgrIlQm5DXtUevgJxTbzzhXZA+GkCs4lQJaO40qiXRUVcLTtneI+kTQ8Pi6vX1ywml4vq8w2W2Jo9wMifNAq0LdWYM0C2h9yoQ5/Od6l+Ujq+qxYNgQf85E=,iv:dmc6PgJzECZzFhFC+MdNjRL7b+ib4IiCAfBoYGv9ido=,tag:b1FOmavj7v9grKFjM1r8Lg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQ2x0Z2EwbEtlbi92NjlD
            WVIzU3JWSEdQdUdSNDNQTnhEV3NUdzFPSUEwCkdFemwxaGRrblFNNHdUbUdHMlJC
            S2thQlBvc1pHT0VHMGdES1BlSjB6T2sKLS0tIGtqbHBQeElvY01YSktXUG9CcUFo
            TEdDK2F2NzBxMTd3aUtOUS83OG00WVUKZpn74jjBGrcLdoV5uVUewUmjr2eHQxmv
            baEWTVvHT+0OkNkWakXHcrbNR4ijZrPTiAiG7LYiDNGN1s7dBDcu6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16lgz0kljjnxc6x858p40pqm020rr8vj3dm2ndn3laryvgnrmkcmst8vrs8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWjhsbkd6alA0ckZPM2gx
            VlBob1crT3Q3cHI0N2J1VmtkMlhPYjZHR0c0Ck5QWTUxbzZpbUdMVkZWUHRNNENw
            YjlxSDd3V0hFcEVKcnplVnc2NU5IOFUKLS0tIHFpVjFFRklremtpT2NFWG9oUWFw
            QUJkVkNoRmQzaDNrT09kUWpQbXoybDAKcRJ9ZVNjq9CYdFbL3wnd1htEAMiwV6d5
            QfYfSQVqqrnNnTsWNbBlklz4/uTK5mFL67ff21/UpyKocmSWGNe6IQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gdgzwd806x9yf6nd7dujuv6wcvnstffwa2eayelgg66cssl6xyaqh6eq96
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T12:58:35Z"
    mac: ENC[AES256_GCM,data:W8s4f3doEZN8/ZipCKU7p8GXe0Raax8aAYCMow4tgWTNWUS7OhaJCpsD2To8hleRnTgjI3kvC4pxN+Mx3MbUHkz+TgZp9lrWICszez3WQ14R6Kvr9RzMsNPFu5KIw6tiqkRIFQxujxBndTmB72LCvXSu0VPd16HsAyL/1R/63P4=,iv:y6jJ7LyMYs90Ty/sz1byTp5tptMXPaEbj/Pw3ROrFBo=,tag:j/ZBZHO8UE6cDoYPcLestw==,type:str]
    version: 3.13.0
