apiVersion: v1
data:
    password: ENC[AES256_GCM,data:flsu7Q72CbWAagk4,iv:BAElwVbQX57SpS1wrYN2ZwvS5h9j2Lj3pfaPFlSMtJ8=,tag:G5g7hmSH1ay224kPCcVutw==,type:str]
    user: ENC[AES256_GCM,data:kLHyF5dcd0U=,iv:JGc4IQcPDslNWgz30ZukzPJ4snEzKKScUjUQwk3YCIg=,tag:LPogVMYg/oPOS45Ki4jrzg==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age1gdgzwd806x9yf6nd7dujuv6wcvnstffwa2eayelgg66cssl6xyaqh6eq96
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bmhZVXJzYVBmN0o1b3Vm
            cXVBa0lCakQxR2w2N2IxTHhmODFlOFEyS0FvCm5CL3NzYlU2Tmd2bFJmYnh1V09p
            TUE4UDN4dWxUR294bk1GYVd3Ym5WVE0KLS0tIFVBemtxTVNrWlBDVVhxUXhadnFH
            S3g3SE9pajREOEdFeDJneGdyR0NOV2cKr5Y+1KGTL2mfViUD1b84GlMHhHuz/JzC
            H/Evl0b9L5dQt+4fp3NhQ4ee+V/SCcIkbLT2ugpB6r+1c6xL8pTDbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-03T19:44:40Z"
    mac: ENC[AES256_GCM,data:EYwc9+lfw5b1NrccrSthVIgBx/KYoUzz1NP9iK9B9cgu0VtURXKfEnHYLHWFhkGMrBSdHzSZbRQvsIapSKV6GDy71I2nI0XvPPvawKPOCKsvmfF9ZzwP9Anxrf+Hhi6IHCS/zKPWGkbplfWaNzHGXJZ71RUo0/al2q1H3HFoDBQ=,iv:55cT33Qp0bu65lAupdrHFCOE7XavIC0PP3/aiFj6oes=,tag:+PUYIgLxM3FSwBWf3YXCmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
