apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:p4KO7BW729OK+XM4D5LuKYmlTCugWKmKM2Gie71XhqWaGD8Jy+2pwEyKPmN10O1pYA0eL4e71EHyxx1XkPleTIxMuUfE9uyaI/czGulu1WZzgqzREj9nJ7B9wY0xsFfUJNBj6QCp6J2k7v2HN9iZHiPzRgLDG/Q+emz2qibatJtxZL2b4w3ZmKZKuG0BBOtISnDibcyd2V3AFssPKoG8+v08NjSmtrRkLLI7547jxq1O0HBBYH2QvARTb6ZreSHGUdmMHr+t+yS+M39k4ydRB/u2eycs+c9a9s/HDPf4SoK92AY36XzrwU3wIiM=,iv:jIR7Yhg80FgdKXALqe4jtL52lbLOaHxldUCIluMNx9M=,tag:gA+IZIfVEXvPJfINdLak6w==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWkMwWFd6Q21ram1NaWVn
            ZDNRZks3NTZJNkZ6cThHU3FJR2lXZklKMFRBCmFwR1RKK3FsM3VuMVpLYnUzS1Mr
            ZGJOTkRRMHRlR0hKVkQyYk9KM25GYjQKLS0tIG1GRnVHTmtlbWU2V3Y2MmZWY1My
            TExPa3VyQ3Q3MWZaSGh0dnpTcWNhZjQKEmChrdYYvJ7BNzGxJEQo9/I2GPJtMS4L
            nwhDf9v00GfslAGeFDDSVS0c8u7Jil69w+ilCPYXxqk3hmBLxniJyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16lgz0kljjnxc6x858p40pqm020rr8vj3dm2ndn3laryvgnrmkcmst8vrs8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYkJ6NHM1NGRTRTlhdjVp
            TlJUbWh1aDE5cnhZYVhETktqNEl3emp0a0drCkx1Qk5MWDZGU3hER3RMUklFMXdI
            dTNGMTFnbnRWZnh1aEZHd0tQL3ZBd0EKLS0tIFJ2bHU2OVU0SzVTZDduZzRXd2pI
            WUREcXU3R3IyTUhCOUhPeTVHaFE3aEEKWkuYS2i6egwRjaqPqyEcaPZ12ufQRrMs
            FmxmFgY80yOYrRQWE8wbvvDlbwgU6jIS8o17B2b91yvmC+RLGRiBcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gdgzwd806x9yf6nd7dujuv6wcvnstffwa2eayelgg66cssl6xyaqh6eq96
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T12:58:35Z"
    mac: ENC[AES256_GCM,data:TldRYEHLK6GLeGDzhfS7v8IcLwUXYDsXFrNExiCm9xC6lALGhYPXlw2PPqmtTi/doqwqdG1RuzEcq54l2pNfW7+DZ7sqNxRa0Pbpsu2MZ+mlkU3chubFdfUPR4GS7rYFcFrwP4r4teIKn58zxQf3iOxswwLw+pReYcUXqOkqlio=,iv:XEJa0U2bOtM5zbFEa1jWoVAqMRj4WgOWXO3HYND3KLo=,tag:4DlzodChMUsc1WR+m2GQ9Q==,type:str]
    version: 3.13.0
